### ISSUE TITLE
"Event origin does not match" type error thrown

### ISSUE THREAD

**Issue by virgilbugnariu** [VISIT-X/vxpay-js#2]
```Uncaught TypeError: Event origin does not match: http://localhost:3000```

This error is being thrown each time we initialize the library. Is there any way we can suppress this? 
I assume in most of the cases this library will be used on domains outside visit-x so I think this check is not necessary.

Thank you :)

**Comment by t1gor** [comment]
Hello, @virgilbugnariu. 

I assume you're running some sort of dev server for rendering the app. This happens when the library gets postMessages from origin that is not VX. In my case, for instance, that was [webpack dev server](https://github.com/webpack/webpack-dev-server). This issue will be resolved in the next release.

>  check is not necessary.

The check itself is to validate the message format, in this case. I will change the code not to throw an error.

**Comment by t1gor** [comment]
Changes available in version 2.0.3 both on [GitHub](https://github.com/VISIT-X/vxpay-js/releases/tag/2.0.3) & [npm](https://www.npmjs.com/package/vxpay-js).

**Comment by virgilbugnariu** [comment]
Hi @t1gor,
Thank you for addressing this issue. 
I just tested the 2.0.3 release and everything is working properly :)

Yes, we are using a development server (react-create-app's one which I believe is also using webpack-dev-server).

By "check is not necessary" what I actually wanted to say is that the app won't be hosted on VX but on a different domain (as far as I know).
Maybe accepting a list of domains instead of only one domain would be an alternative solution?

Thanks :)

**Comment by t1gor** [comment]
> Maybe accepting a list of domains instead of only one domain would be an alternative solution?

Sure, but what's the use case for that? We're only expecting VX to be sending those events. The events that trigger the error are the dev server event for live reloading.

**Comment by virgilbugnariu** [comment]
Oh I understand. Thank you for clarifying :)
